"""Deterministic signal-family rules used by Step 3 classification.

These rules are intentionally simple and auditable:
- transparent keyword/phrase hits with optional anchors/overrides
- explicit exclusions to prevent common false positives

They are *not* the high-recall retrieval layer; retrieval happens in Step 3
discovery (lexical keywords + optional embeddings).
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class SignalFamilyRule:
    """Transparent keyword rules with optional anchors/overrides.

    This is a deterministic, auditable matcher used by Step 3.

    - `keywords`: general terms counted toward `min_hits`
    - `anchors`: high-precision topic anchors required for a match (optional)
    - `overrides`: strong phrases that can match even when keywords are sparse
      (still subject to exclusions)
    """

    keywords: list[str]
    exclusions: list[str]
    min_hits: int = 1
    anchors: list[str] = field(default_factory=list)
    min_anchor_hits: int = 0
    overrides: list[str] = field(default_factory=list)


RULES_BY_SLUG: dict[str, SignalFamilyRule] = {
    "fomc_surprises": SignalFamilyRule(
        keywords=[
            "fomc",
            "fed",
            "federal reserve",
            "powell",
            "rate hike",
            "rate cut",
            "interest rate",
            "basis points",
            "bps",
            "meeting",
            "federal funds rate",
            "fed chair",
            "chair",
        ],
        exclusions=[
            # Disambiguate other central bank decision templates.
            "bank of japan",
            "boj",
            "bank of england",
            "boe",
            "bank of canada",
            "bank of mexico",
            "ecb",
        ],
        # Restrict strict matching to higher-signal FOMC markets.
        #
        # Rationale:
        # "Fed ladder" templates (e.g., "Will 6 Fed rate cuts happen in 2026?")
        # can be abundant and dominate downstream relevance ranking. These often
        # contain only 1–2 generic terms ("fed", "rate cut") and are better kept
        # as discovery-only, while meeting/decision/chair markets remain strict.
        min_hits=3,
        anchors=[
            "fomc",
            "fed",
            "federal reserve",
            "powell",
            "federal funds rate",
        ],
        min_anchor_hits=1,
        overrides=[
            "federal open market committee",
            "fed chair",
            "federal reserve chair",
        ],
    ),
    "real_yields_long_rates": SignalFamilyRule(
        keywords=[
            "real yield",
            "real yields",
            "treasury yield",
            "10-year yield",
            "10 year yield",
            "10y yield",
            "long rates",
            "bond yields",
            "breakeven inflation",
        ],
        # Prevent obvious false positives from generic "10 year(s)" phrases.
        exclusions=[
            "sentenced",
            "years in prison",
            "in prison",
        ],
        min_hits=1,
    ),
    "us_china_semis_export_controls": SignalFamilyRule(
        keywords=[
            "export controls",
            "export control",
            "export restrictions",
            "export restriction",
            "export license",
            "export licensing",
            "bis",
            "entity list",
            "commerce department",
            "bureau of industry and security",
            "chip ban",
            "asml",
            "euv",
            "duv",
            "semiconductor equipment",
            "advanced chips",
            "semiconductor",
            "nvidia",
            "tsmc",
            "smic",
            "huawei",
            "h20",
            "h100",
            "a100",
            "china",
        ],
        exclusions=[],
        anchors=[
            "export controls",
            "export control",
            "export restrictions",
            "export restriction",
            "export license",
            "export licensing",
            "bis",
            "entity list",
            "bureau of industry and security",
            "commerce department",
        ],
        min_anchor_hits=1,
        min_hits=1,
        overrides=[
            "entity list",
            "export license",
            "export controls",
            "chip export restrictions",
        ],
    ),
    "taiwan_geopolitical_risk": SignalFamilyRule(
        keywords=[
            "taiwan",
            "taiwan strait",
            "china",
            "invasion",
            "blockade",
        ],
        exclusions=[],
        min_hits=2,
    ),
    "crypto_regime_changes": SignalFamilyRule(
        # Precision note:
        # We require at least one explicit regulatory/legislative anchor to avoid
        # classifying pure price-target markets (e.g. "Will XRP reach $4?") as
        # "regime changes".
        keywords=[
            "sec",
            "cftc",
            "crypto regulation",
            "digital asset",
            "digital assets",
            "stablecoin",
            "stablecoins",
            "stablecoin bill",
            "enforcement",
            "lawsuit",
            "sues",
            "approval",
            "approved",
            "spot etf",
            "bitcoin etf",
            "ethereum etf",
            "crypto etf",
            "mica",
            # Entities are allowed as supporting evidence but not sufficient alone.
            "coinbase",
            "binance",
            "kraken",
            "ripple",
            "xrp",
        ],
        exclusions=[
            # Disambiguate SEC(sports) vs SEC(regulator)
            "regular season",
            "women's",
            "women’s",
            "men's",
            "men’s",
            "team",
            "ncaa",
            "basketball",
            "football",
            "soccer",
            "mlb",
            "nba",
            "nfl",
            "nhl",
            "ufc",
            "fifa",
            "world cup",
        ],
        anchors=[
            "sec",
            "cftc",
            "stablecoin",
            "stablecoins",
            "spot etf",
            "bitcoin etf",
            "ethereum etf",
            "crypto etf",
            "crypto regulation",
            "digital assets",
            "enforcement",
            "lawsuit",
            "sues",
            "mica",
        ],
        min_anchor_hits=1,
        min_hits=1,
        overrides=[
            "strategic bitcoin reserve",
            "national bitcoin reserve",
            "bitcoin reserve",
        ],
    ),
    "ai_regulation_big_tech_enforcement": SignalFamilyRule(
        # Precision note:
        # This family is about regulation/enforcement, not "who has the best AI model"
        # or generic Big Tech company chatter.
        keywords=[
            "ai act",
            "ai regulation",
            "ai safety bill",
            "ai bill",
            "ai legislation",
            "ai law",
            "model regulation",
            "frontier model",
            "antitrust",
            "doj",
            "department of justice",
            "ftc",
            "federal trade commission",
            "platform regulation",
            "digital services act",
            "digital markets act",
            "dma",
            "dsa",
            "privacy sandbox",
            "adtech",
            "ad tech",
            "competition",
            "gatekeeper",
            "fine",
            "injunction",
            "remedy",
            "settlement",
            "lawsuit",
            "sues",
            "copyright",
        ],
        exclusions=[
            # Model leaderboard / "best model" templates (not regulation/enforcement)
            "best ai model",
            "chatbot arena",
            "#1 ai model",
            "first company to have an ai model",
            # Generic corporate rank/market cap templates
            "largest company",
            "market cap",
            # M&A templates (not regulation/enforcement)
            "acquired",
            "acquire",
            "acquisition",
            "merger",
            "ipo",
        ],
        anchors=[
            "antitrust",
            "doj",
            "department of justice",
            "ftc",
            "federal trade commission",
            "digital markets act",
            "dma",
            "digital services act",
            "dsa",
            "ai act",
            "ai regulation",
            "ai safety bill",
            "ai bill",
            "ai legislation",
            "ai law",
            "regulation",
            "lawsuit",
            "sues",
            "fine",
            "injunction",
            "remedy",
            "settlement",
            "european commission",
            "eu commission",
            "copyright",
        ],
        min_anchor_hits=1,
        min_hits=1,
    ),
    "datacenter_power_grid_constraints": SignalFamilyRule(
        keywords=[
            # Avoid matching generic "power" markets (e.g., "Balance of Power").
            # Require co-occurrence (min_hits>=2) across these more specific terms.
            "datacenter",
            "data center",
            "datacenter power",
            "data center power",
            "moratorium",
            "power grid",
            "grid",
            "electricity",
            "interconnection",
            "substation",
            "transmission",
            "utility",
            "nuclear power",
            "smr",
            "interconnection queue",
            "load growth",
            "electricity demand",
            "power demand",
            "grid capacity",
            "transmission line",
            "gas plant",
            "natural gas plant",
            "permitting",
            "permit",
            "zoning",
        ],
        exclusions=[
            # Political template markets
            "balance of power",
            "nuclear option",
            "filibuster",
        ],
        min_hits=2,
    ),
    "antitrust_platforms_app_stores_ads": SignalFamilyRule(
        keywords=[
            # Platform/app store / DMA vocabulary
            "app store",
            "google play",
            "sideload",
            "sideloading",
            "digital markets act",
            "dma",
            "digital services act",
            "dsa",
            "adtech",
            "advertising market",
            "ad tech",
            "google ads",
            "search monopoly",
            "self-preferencing",
            "gatekeeper",
            "store commission",
            "in-app purchase",
            "iap",
            "app store fees",
            "open app markets act",
            "epic games",
            # Enforcement/regulator vocabulary: require co-occurrence with platform terms.
            "antitrust",
            "doj",
            "department of justice",
            "ftc",
            "federal trade commission",
            "competition",
            "european commission",
            "eu commission",
            "lawsuit",
            "sues",
            "fine",
            "monopoly",
            "break up",
            # Common targets (only useful with min_hits>=2)
            "apple",
            "google",
            "meta",
            "amazon",
        ],
        exclusions=[
            # Hard exclusions: app chart / ranking markets (not antitrust enforcement).
            "#1",
            "#2",
            "#3",
            "#4",
            "#5",
            "top 10",
            "top-10",
            "free app",
            "paid app",
            "grossing",
            "downloads",
            "app store charts",
            "google play charts",
            "ranked",
            "ranking",
            "trending",
            # Avoid sports template markets if a generic term slips in.
            "regular season",
            "women's",
            "women’s",
            "men's",
            "men’s",
            "team",
            "ncaa",
            "basketball",
            "football",
            "soccer",
        ],
        # Require a regulator/competition anchor so company names don't explode recall.
        anchors=[
            "antitrust",
            "doj",
            "department of justice",
            "ftc",
            "federal trade commission",
            "digital markets act",
            "dma",
            "digital services act",
            "competition",
            "european commission",
            "eu commission",
            "lawsuit",
            "sues",
            "fine",
            "monopoly",
            "break up",
        ],
        min_anchor_hits=1,
        # Require at least two total hits so a single token like "app store" or "ftc"
        # doesn't create a strict match by itself.
        min_hits=2,
        overrides=[
            "digital markets act",
            "open app markets act",
            "app store lawsuit",
            "google adtech",
            "privacy sandbox",
        ],
    ),
    "it_spending_cycle_enterprise_cloud_ai": SignalFamilyRule(
        keywords=[
            "it spending",
            "enterprise spending",
            "cloud spending",
            "capex",
            "saas",
            "aws",
            "azure",
            "gcp",
            "google cloud",
            "enterprise it",
            "enterprise software",
            "software spending",
            "subscription software",
            "datacenter capex",
            "data center capex",
            "ai capex",
            "hyperscaler",
            # AI compute cost proxies (helps recover GPU rental / index markets).
            "gpu rental",
            "gpu rental prices",
            "gpu pricing",
            "compute pricing",
            "h100 index",
        ],
        exclusions=[],
        min_hits=1,
    ),
    "healthcare_policy_reimbursement": SignalFamilyRule(
        keywords=[
            "medicare",
            "medicaid",
            "cms",
            "medicare part d",
            "medicare part b",
            "reimbursement",
            "reimbursement rate",
            "payment rate",
            "healthcare policy",
            "coverage",
            "medicare advantage",
            "medicaid expansion",
            "premium",
            "premium subsidy",
            "aca subsidies",
            "insurance",
            "uninsured",
            "drug pricing",
            "price negotiation",
            "pbm",
            "pharmacy benefit manager",
            "formulary",
            "marketplace",
            "exchange",
            "aca",
            "obamacare",
            "hhs",
        ],
        exclusions=[
            "fantasy",
        ],
        # "insurance"/"premium" are broad. Require at least one anchor to avoid
        # matching generic insurance chatter that isn't about healthcare policy.
        anchors=[
            "medicare",
            "medicaid",
            "cms",
            "hhs",
            "aca",
            "obamacare",
            "reimbursement",
            "drug pricing",
            "price negotiation",
            "pbm",
            "medicare advantage",
            "medicare part d",
        ],
        min_anchor_hits=1,
        min_hits=1,
        overrides=[
            "medicare for all",
            "drug price negotiation",
            "medicare negotiation",
            "cms rule",
            "medicaid expansion",
            "medicare part d",
            "premium subsidies",
            "aca subsidies",
            "pbm reform",
        ],
    ),
    "consumer_credit_conditions_cycle": SignalFamilyRule(
        keywords=[
            "credit card",
            "delinquency",
            "default",
            "consumer credit",
            "mortgage",
            "loan",
        ],
        exclusions=[],
        min_hits=1,
    ),
}
